name: Railway Logs (manual)

on:
  workflow_dispatch:
    inputs:
      lines:
        description: "Сколько строк показать (tail)"
        required: false
        default: "400"
      service_id:
        description: "Override Railway SERVICE_ID (опционально)"
        required: false
        default: ""
      environment_id:
        description: "Override Railway ENVIRONMENT_ID (опционально)"
        required: false
        default: ""
      deployment_id:
        description: "DEPLOYMENT_ID (или оставьте пустым)"
        required: false
        default: ""
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  logs:
    runs-on: ubuntu-latest

    # Важно: CLI читает токен из RAILWAY_TOKEN (env).
    env:
      RAILWAY_TOKEN:      ${{ secrets.RAILWAY_TOKEN }}
      R_SERVICE_ID_DEF:   ${{ secrets.RAILWAY_SERVICE_ID }}
      R_ENV_ID_DEF:       ${{ secrets.RAILWAY_ENV_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (для Railway CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Validate required secrets
        run: |
          set -e
          test -n "${RAILWAY_TOKEN}" || (echo "❌ Missing secret: RAILWAY_TOKEN" && exit 1)
          echo "✅ RAILWAY_TOKEN present"
          # SERVICE/ENV можно задавать либо secrets, либо inputs.
          if [ -z "${{ github.event.inputs.service_id }}" ] && [ -z "${R_SERVICE_ID_DEF}" ]; then
            echo "❌ Need SERVICE_ID via inputs.service_id or secret RAILWAY_SERVICE_ID"; exit 1; fi
          if [ -z "${{ github.event.inputs.environment_id }}" ] && [ -z "${R_ENV_ID_DEF}" ]; then
            echo "❌ Need ENVIRONMENT_ID via inputs.environment_id or secret RAILWAY_ENV_ID"; exit 1; fi

      - name: Install Railway CLI
        run: |
          npm i -g @railway/cli@latest
          railway --version

      # Для токена проекта whoami может вернуть Unauthorized — это нормально.
      - name: Who am I (optional)
        run: |
          railway whoami || echo "ℹ️ whoami unauthorized (OK for project tokens)"

      - name: Fetch logs (JSON)
        id: fetch
        run: |
          set -Eeuo pipefail

          LINES="${{ github.event.inputs.lines || '400' }}"
          SERVICE_ID="${{ github.event.inputs.service_id }}"
          ENV_ID="${{ github.event.inputs.environment_id }}"
          DEPLOYMENT_ID="${{ github.event.inputs.deployment_id }}"

          # Фолбэк к secrets, если inputs пустые
          if [ -z "$SERVICE_ID" ]; then SERVICE_ID="$R_SERVICE_ID_DEF"; fi
          if [ -z "$ENV_ID" ];    then ENV_ID="$R_ENV_ID_DEF"; fi

          if [ -n "$DEPLOYMENT_ID" ]; then
            DEP_ARG="--deployment $DEPLOYMENT_ID"
          else
            DEP_ARG=""
          fi

          # В CLI v4 нет --project у `railway logs`. Достаточно токена + ID.
          railway logs --service "$SERVICE_ID" --environment "$ENV_ID" $DEP_ARG --json > logs.json

          tail -n "$LINES" logs.json | tee tail.txt

          {
            echo "tail<<'EOF'"
            tail -n "$LINES" logs.json
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Summary
        run: |
          echo "### Railway logs (last ${{ github.event.inputs.lines || '400' }} lines)" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo '```json' >> "$GITHUB_STEP_SUMMARY"
          cat tail.txt >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: railway-logs
          path: |
            logs.json
            tail.txt
          retention-days: 7

      - name: Comment logs to PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ github.token }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Railway logs (last ${{ github.event.inputs.lines || '400' }} lines)
            ```json
            ${{ steps.fetch.outputs.tail }}
            ```
