name: Railway Logs (manual)

on:
  workflow_dispatch:
    inputs:
      lines:
        description: 'Number of lines to show'
        required: false
        default: '400'

jobs:
  logs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Node, чтобы работал npx
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 2) Подготовка инструментов и выбор команды Railway
      - name: Prepare CLI (railway / jq) and detect command
        id: prep
        shell: bash
        run: |
          set -euo pipefail
          echo "PATH=$PATH"

          # jq для парсинга JSON (не критично, но удобно)
          sudo apt-get update -y
          sudo apt-get install -y jq >/dev/null

          # Попытка №1: npx CLI
          if npx -y @railway/cli@latest --version >/dev/null 2>&1; then
            echo "cmd=npx -y @railway/cli@latest" >> $GITHUB_OUTPUT
            echo "Using Railway via npx"
            exit 0
          fi

          # Попытка №2: curl-инсталлятор
          curl -fsSL https://railway.app/install.sh | sh
          if "$HOME/.railway/bin/railway" --version >/dev/null 2>&1; then
            echo "cmd=$HOME/.railway/bin/railway" >> $GITHUB_OUTPUT
            echo "Using Railway via ~/.railway/bin/railway"
            exit 0
          fi

          echo "::error::Railway CLI not found (npx and curl installer both failed)."
          exit 127

      # 3) Логин
      - name: Login to Railway
        shell: bash
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          set -euo pipefail
          if [ -z "${RAILWAY_TOKEN:-}" ]; then
            echo "::error::Missing secret RAILWAY_TOKEN in GitHub → Settings → Secrets → Actions"
            exit 1
          fi
          "${{ steps.prep.outputs.cmd }}" login --token "$RAILWAY_TOKEN"

      # 4) Получение логов (с ID или автоопределением)
      - name: Fetch logs
        shell: bash
        env:
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
          RAILWAY_ENV_ID:     ${{ secrets.RAILWAY_ENV_ID }}
        run: |
          set -euo pipefail
          LINES="${{ github.event.inputs.lines }}"
          CMD='${{ steps.prep.outputs.cmd }}'

          ARGS=( --json --lines "$LINES" )
          [[ -n "${RAILWAY_PROJECT_ID:-}" ]] && ARGS+=( --project "$RAILWAY_PROJECT_ID" )
          [[ -n "${RAILWAY_SERVICE_ID:-}" ]] && ARGS+=( --service "$RAILWAY_SERVICE_ID" )
          [[ -n "${RAILWAY_ENV_ID:-}"     ]] && ARGS+=( --environment "$RAILWAY_ENV_ID" )

          # Если ID не заданы, пробуем автоопределить
          if [[ -z "${RAILWAY_PROJECT_ID:-}" || -z "${RAILWAY_SERVICE_ID:-}" ]]; then
            $CMD status --json > status.json || true
            PID=$(jq -r '.project.id // empty' status.json 2>/dev/null || echo "")
            SID=$(jq -r '.services[0].id // empty' status.json 2>/dev/null || echo "")
            [[ -n "$PID" ]] && ARGS+=( --project "$PID" )
            [[ -n "$SID" ]] && ARGS+=( --service "$SID" )
          fi

          echo "$CMD logs ${ARGS[*]}"
          # shellcheck disable=SC2068
          $CMD logs ${ARGS[@]} > railway_logs.json

          jq -r '.logs[]?.message // empty' railway_logs.json | tail -n "$LINES" > railway_logs.txt || true

      # 5) Артефакты + Summary
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: railway-logs
          path: |
            railway_logs.json
            railway_logs.txt

      - name: Summary
        shell: bash
        run: |
          echo "### Railway logs (last ${{ github.event.inputs.lines }} lines)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          tail -n "${{ github.event.inputs.lines }}" railway_logs.txt >> $GITHUB_STEP_SUMMARY || true
          echo '```' >> $GITHUB_STEP_SUMMARY
