name: Railway Logs (manual)

on:
  workflow_dispatch:
    inputs:
      lines:
        description: 'Number of lines'
        required: false
        default: '400'

jobs:
  logs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Railway CLI and jq
        run: |
          set -euo pipefail
          npm i -g @railway/cli
          railway --version
          sudo apt-get update -y
          sudo apt-get install -y jq

      # НИКАКОГО login тут не делаем — токен отдаём шагу с логами
      - name: Fetch logs
        env:
          RAILWAY_TOKEN:    ${{ secrets.RAILWAY_TOKEN }}      # обязателен
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }} # желательно
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }} # желательно
          RAILWAY_ENV_ID:     ${{ secrets.RAILWAY_ENV_ID }}     # опционально
        run: |
          set -euo pipefail
          LINES="${{ github.event.inputs.lines }}"

          # Если токена нет — сразу подсказка
          if [ -z "${RAILWAY_TOKEN:-}" ]; then
            echo "::error::Missing secret RAILWAY_TOKEN in GitHub → Settings → Secrets → Actions"; exit 1
          fi

          # Сбор аргументов
          ARGS=( --json --lines "$LINES" )
          [[ -n "${RAILWAY_PROJECT_ID:-}" ]] && ARGS+=( --project "$RAILWAY_PROJECT_ID" )
          [[ -n "${RAILWAY_SERVICE_ID:-}" ]] && ARGS+=( --service "$RAILWAY_SERVICE_ID" )
          [[ -n "${RAILWAY_ENV_ID:-}"     ]] && ARGS+=( --environment "$RAILWAY_ENV_ID" )

          # Если ID не задали — автоопределим
          if [[ -z "${RAILWAY_PROJECT_ID:-}" || -z "${RAILWAY_SERVICE_ID:-}" ]]; then
            railway status --json > status.json || true
            PID=$(jq -r '.project.id // empty' status.json 2>/dev/null || echo "")
            SID=$(jq -r '.services[0].id // empty' status.json 2>/dev/null || echo "")
            [[ -n "$PID" ]] && ARGS+=( --project "$PID" )
            [[ -n "$SID" ]] && ARGS+=( --service "$SID" )
          fi

          echo "railway logs ${ARGS[*]}"
          # shellcheck disable=SC2068
          railway logs ${ARGS[@]} > railway_logs.json

          jq -r '.logs[]?.message // empty' railway_logs.json | tail -n "$LINES" > railway_logs.txt || true

      - uses: actions/upload-artifact@v4
        with:
          name: railway-logs
          path: |
            railway_logs.json
            railway_logs.txt

      - name: Summary
        run: |
          echo "### Railway logs (last ${{ github.event.inputs.lines }} lines)" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          tail -n "${{ github.event.inputs.lines }}" railway_logs.txt >> $GITHUB_STEP_SUMMARY || true
          echo '```' >> $GITHUB_STEP_SUMMARY
