name: Railway Logs (manual)

on:
  workflow_dispatch:
    inputs:
      lines:
        description: "Сколько строк показать (tail)"
        required: false
        default: "400"
      service_id:
        description: "Override SERVICE_ID (опционально)"
        required: false
        default: ""
      environment_id:
        description: "Override ENVIRONMENT_ID (опционально)"
        required: false
        default: ""
      deployment_id:
        description: "Опционально: DEPLOYMENT_ID (или оставьте пустым)"
        required: false
        default: ""
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  logs:
    runs-on: ubuntu-latest

    env:
      # Ключевое: CLI возьмёт токен из этой переменной
      RAILWAY_TOKEN:      ${{ secrets.RAILWAY_TOKEN }}
      RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
      RAILWAY_ENV_ID:     ${{ secrets.RAILWAY_ENV_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (for Railway CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Railway CLI
        run: |
          npm i -g @railway/cli@latest
          railway --version

      # Безопасная самопроверка: секрет на месте?
      - name: Validate required secrets
        run: |
          set -e
          test -n "${RAILWAY_TOKEN:-}" || (echo "❌ RAILWAY_TOKEN is empty" && exit 1)
          echo "RAILWAY_TOKEN length: ${#RAILWAY_TOKEN} (значение замаскировано в логах)"

      # Проверка авторизации — должна показать пользователя, иначе токен неверный
      - name: Who am I
        run: |
          set -e
          railway whoami

      # Забираем логи напрямую флагами (без railway use / без --project)
      - name: Fetch logs (JSON)
        id: fetch
        run: |
          set -euo pipefail

          LINES="${{ github.event.inputs.lines || '400' }}"
          SERVICE_ID="${{ github.event.inputs.service_id || env.RAILWAY_SERVICE_ID }}"
          ENV_ID="${{ github.event.inputs.environment_id || env.RAILWAY_ENV_ID }}"
          DEPLOYMENT_ID="${{ github.event.inputs.deployment_id || '' }}"

          DEP_ARG=""
          if [ -n "$DEPLOYMENT_ID" ]; then
            DEP_ARG="--deployment $DEPLOYMENT_ID"
          fi

          railway logs --service "$SERVICE_ID" --environment "$ENV_ID" $DEP_ARG --json > logs.json

          tail -n "$LINES" logs.json | tee tail.txt

          {
            echo "tail<<'EOF'"
            tail -n "$LINES" logs.json
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Summary
        run: |
          echo "### Railway logs (last ${{ github.event.inputs.lines || '400' }} lines)" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo '```json' >> "$GITHUB_STEP_SUMMARY"
          cat tail.txt >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: railway-logs
          path: |
            logs.json
            tail.txt
          retention-days: 7

      - name: Comment logs to PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ github.token }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Railway logs (last ${{ github.event.inputs.lines || '400' }} lines)
            ```json
            ${{ steps.fetch.outputs.tail }}
            ```
