name: Railway Token Check
on: workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm i -g @railway/cli@latest
      - name: Test token + try logs
        env:
          RAILWAY_TOKEN:      ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
          RAILWAY_ENV_ID:     ${{ secrets.RAILWAY_ENV_ID }}
        run: |
          set -e
          echo "Has token? $([ -n "$RAILWAY_TOKEN" ] && echo YES || echo NO)"
          # whoami для project token'а часто пишет Unauthorized — это нормально;
          # главное, чтобы logs сработал.
          railway whoami || echo "whoami unauthorized (OK for project token)"
          railway logs --service "$RAILWAY_SERVICE_ID" --environment "$RAILWAY_ENV_ID" --json | head -n 5
          echo "✅ Token works"
