name: Railway Logs (manual)

on:
  workflow_dispatch:

jobs:
  logs:
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Fetch logs
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
          RAILWAY_ENV_ID: ${{ secrets.RAILWAY_ENV_ID }}  # опционально
        run: |
          ~/.railway/bin/railway login --token "$RAILWAY_TOKEN"
          ~/.railway/bin/railway logs \
            --project $RAILWAY_PROJECT_ID \
            --service $RAILWAY_SERVICE_ID \
            ${RAILWAY_ENV_ID:+--environment $RAILWAY_ENV_ID} \
            --lines 200 > railway_logs.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: railway-logs
          path: railway_logs.txt
