name: Railway Logs (manual)

on:
  workflow_dispatch:
    inputs:
      lines:
        description: "Сколько строк показать (tail)"
        required: false
        default: "400"
      service_id:
        description: "Override Railway SERVICE_ID (опционально)"
        required: false
        default: ""
      environment_id:
        description: "Override Railway ENV_ID (опционально)"
        required: false
        default: ""
      deployment_id:
        description: "DEPLOYMENT_ID или спец-значение __build для --build"
        required: false
        default: ""
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  logs:
    runs-on: ubuntu-latest

    env:
      RAILWAY_TOKEN:      ${{ secrets.RAILWAY_TOKEN }}
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }} # не используем в командах, но пусть будет
      RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
      RAILWAY_ENV_ID:     ${{ secrets.RAILWAY_ENV_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (для Railway CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Validate secrets
        run: |
          set -e
          for v in RAILWAY_TOKEN RAILWAY_SERVICE_ID RAILWAY_ENV_ID; do
            if [ -z "${!v}" ]; then
              echo "::error::Missing required secret/env: $v"
              exit 1
            fi
          done

      - name: Install Railway CLI
        run: |
          npm i -g @railway/cli@latest
          railway --version
          railway whoami || true

      - name: Fetch logs (JSON)
        id: fetch
        run: |
          set -euo pipefail
          LINES="${{ github.event.inputs.lines || '400' }}"
          SERVICE_ID="${{ github.event.inputs.service_id || env.RAILWAY_SERVICE_ID }}"
          ENV_ID="${{ github.event.inputs.environment_id || env.RAILWAY_ENV_ID }}"
          DEPLOYMENT_IN="${{ github.event.inputs.deployment_id || '' }}"

          DEP_ARG=""
          if [ -n "$DEPLOYMENT_IN" ]; then
            if [ "$DEPLOYMENT_IN" = "__build" ]; then
              DEP_ARG="--build"
            else
              DEP_ARG="--deployment $DEPLOYMENT_IN"
            fi
          fi

          # ВАЖНО: никаких --project и никаких `railway use`
          railway logs --service "$SERVICE_ID" --environment "$ENV_ID" $DEP_ARG --json > logs.json

          tail -n "$LINES" logs.json | tee tail.txt

          {
            echo "lines=$LINES"
            echo "tail<<'EOF'"
            tail -n "$LINES" logs.json
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Summary
        run: |
          {
            echo "### Railway logs (last ${{ steps.fetch.outputs.lines }} lines)"
            echo
            echo '```json'
            cat tail.txt
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: railway-logs
          path: |
            logs.json
            tail.txt
          retention-days: 7

      - name: Comment logs to PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ github.token }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Railway logs (last ${{ steps.fetch.outputs.lines }} lines)
            ```json
            ${{ steps.fetch.outputs.tail }}
            ```
