
name: Railway Logs (PR comment)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  comment-logs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Railway CLI
        run: npm i -g @railway/cli
      - name: Fetch latest 200 lines
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          set -euo pipefail
          railway logs --json -n 200 > railway_logs.json
          jq -r '.logs[]?.message // empty' railway_logs.json | tail -n 200 > railway_logs.txt || true
      - name: Prepare tail content
        id: tail
        run: |
          CONTENT="$(tail -n 200 railway_logs.txt)"
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "${CONTENT}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ### Railway Runtime Logs (last 200)
            ```
            ${{ steps.tail.outputs.content }}
            ```
