name: Railway Build Logs (manual)
run-name: Railway Build Logs (manual)

on:
  workflow_dispatch:
    inputs:
      lines:
        description: "Сколько строк вывести (tail)"
        required: false
        default: "400"

permissions:
  contents: read
  pull-requests: write

jobs:
  logs:
    runs-on: ubuntu-latest

    env:
      # ВАЖНО: здесь именно project token (36 символов) из Project → Settings → Tokens
      RAILWAY_TOKEN:      ${{ secrets.RAILWAY_TOKEN }}
      RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
      RAILWAY_ENV_ID:     ${{ secrets.RAILWAY_ENV_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (для Railway CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Railway CLI
        run: |
          npm i -g @railway/cli@latest
          railway --version

      # whoami с project token в CI часто Unauthorized — это нормально
      - name: Who am I (informative)
        continue-on-error: true
        run: railway whoami

      - name: Fetch latest BUILD logs (JSON)
        id: fetch
        run: |
          set -Eeuo pipefail
          LINES="${{ github.event.inputs.lines || '400' }}"

          # Build-логи (а не runtime) — стабильны в CI с project token
          railway logs \
            --build \
            --service "$RAILWAY_SERVICE_ID" \
            --environment "$RAILWAY_ENV_ID" \
            --json > build-logs.json

          tail -n "$LINES" build-logs.json | tee tail.txt

          {
            echo "tail<<'EOF'"
            tail -n "$LINES" build-logs.json
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Summary
        run: |
          echo "### Railway build logs (last ${{ github.event.inputs.lines || '400' }} lines)" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo '```json' >> "$GITHUB_STEP_SUMMARY"
          cat tail.txt >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: railway-build-logs
          path: |
            build-logs.json
            tail.txt
          retention-days: 7

      - name: Comment logs to PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ github.token }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Railway build logs (tail)
            ```json
            ${{ steps.fetch.outputs.tail }}
            ```
